version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: true
    TF_INPUT: 0
    TF_VAR_owner_email: pttp@justice.gov.uk
    TF_VAR_env: $ENV
    TF_VAR_enable_critical_notifications: true
    TF_VAR_grafana_db_backup_retention_period: 7
  parameter-store:
    TF_VAR_meta_data_url: "/codebuild/pttp-ci-infrastructure-core-pipeline/meta_data_url"
    TF_VAR_critical_notification_recipients: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/critical_notification_recipients"
    TF_VAR_grafana_admin_password: "/codebuild/pttp-ci-ima-pipeline/$ENV/grafana_admin_password"
    TF_VAR_assume_role: "/codebuild/pttp-ci-ima-pipeline/$ENV/assume_role"
    TF_VAR_grafana_db_username: "/codebuild/pttp-ci-ima-pipeline/$ENV/grafana_db_username"
    TF_VAR_grafana_db_password: "/codebuild/pttp-ci-ima-pipeline/$ENV/grafana_db_password"

phases:
  install:
    commands:
      - wget --no-verbose -O terraform.zip https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /bin

  build:
    commands:
      - export AWS_DEFAULT_REGION=eu-west-2
      - terraform init -no-color --backend-config="key=terraform.$ENV.state"
      - terraform workspace new $ENV || true
      - terraform workspace select $ENV
      - if [$ENV -eq "development"]
      - then
      -   terraform apply --auto-approve -no-color
      - fi
