version: 0.2

env:
  variables:
    TF_INPUT: 0
    TF_VAR_env: $ENV
    TF_IN_AUTOMATION: true
    TF_VAR_enable_transit_gateway: true
    TF_VAR_owner_email: pttp@justice.gov.uk
    TF_VAR_enable_critical_notifications: true
  parameter-store:
    TF_VAR_assume_role: "/codebuild/pttp-ci-ima-pipeline/$ENV/assume_role"
    TF_VAR_meta_data_url: "/codebuild/pttp-ci-infrastructure-core-pipeline/meta_data_url"
    TF_VAR_grafana_db_name: "/codebuild/pttp-ci-ima-pipeline/$ENV/grafana_db_name"
    TF_VAR_grafana_db_endpoint: "/codebuild/pttp-ci-ima-pipeline/$ENV/grafana_db_endpoint"
    TF_VAR_grafana_db_username: "/codebuild/pttp-ci-ima-pipeline/$ENV/grafana_db_username"
    TF_VAR_grafana_db_password: "/codebuild/pttp-ci-ima-pipeline/$ENV/grafana_db_password"
    TF_VAR_grafana_admin_username: "/codebuild/pttp-ci-ima-pipeline/$ENV/grafana_admin_username"
    TF_VAR_grafana_admin_password: "/codebuild/pttp-ci-ima-pipeline/$ENV/grafana_admin_password"
    TF_VAR_vpn_hosted_zone_id: "/codebuild/pttp-ci-ima-pipeline/$ENV/vpn_hosted_zone_id"
    TF_VAR_vpn_hosted_zone_domain: "/codebuild/pttp-ci-ima-pipeline/$ENV/vpn_hosted_zone_domain"
    TF_VAR_smtp_user: "/codebuild/pttp-ci-ima-pipeline/$ENV/smtp_user"
    TF_VAR_smtp_password: "/codebuild/pttp-ci-ima-pipeline/$ENV/smtp_password"
    TF_VAR_domain_prefix: "/codebuild/pttp-ci-ima-pipeline/$ENV/domain_prefix"
    TF_VAR_azure_ad_client_id: "/codebuild/pttp-ci-ima-pipeline/$ENV/azure_ad_client_id"
    TF_VAR_azure_ad_client_secret: "/codebuild/pttp-ci-ima-pipeline/$ENV/azure_ad_client_secret"
    TF_VAR_azure_ad_auth_url: "/codebuild/pttp-ci-ima-pipeline/$ENV/azure_ad_auth_url"
    TF_VAR_azure_ad_token_url: "/codebuild/pttp-ci-ima-pipeline/$ENV/azure_ad_token_url"
    TF_VAR_transit_gateway_id: "/codebuild/pttp-ci-ima-pipeline/$ENV/transit_gateway_id"
    TF_VAR_transit_gateway_route_table_id: "/codebuild/pttp-ci-ima-pipeline/$ENV/transit_gateway_route_table_id"
    TF_VAR_critical_notification_recipients: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/critical_notification_recipients"
    TF_VAR_sns_subscribers: "/codebuild/pttp-ci-ima-pipeline/$ENV/sns_subscribers"
    
    TF_VAR_pentesting_vm_ami_id: "/staff-device/bsi_testing/pentesting_vm_ami_id"                       # Temporary for pen test, created in paramter store.
    TF_VAR_pentesting_vm_ami_ingress_cidrs: "/staff-device/bsi_testing/pentesting_vm_ami_ingress_cidrs" # Temporary for pen test, created in paramter store.

phases:
  install:
    commands:
      - wget --no-verbose -O terraform.zip https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /bin

  build:
    commands:
      - export AWS_DEFAULT_REGION=eu-west-2
      - terraform --version
      - terraform init -no-color --backend-config="key=terraform.$ENV.state"
      - terraform providers
      - terraform workspace new $ENV || true
      - terraform workspace select $ENV
      - terraform apply --auto-approve -no-color

  post_build:
    commands:
      - cd test/
      - docker-compose up -d
      - bundle install
      - bundle exec rspec --format documentation
