apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-configmap
data:
  alertmanager.yml: |
    route:
      receiver: 'default-receiver'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      group_by: ['...']
    receivers:
      - name: 'default-receiver'


