apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-alertmanager
spec:
  selector:
    app: alertmanager
  ports:
    - name: http
      protocol: TCP
      port: 9093
      targetPort: 9093