apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: {{ .Values.prometheus.image }}:latest
        command: ["prometheus"]
        args: 
          - "--config.file=/config/prometheus.yml"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: configuration
          mountPath: "/config"
          readOnly: true
        - name: alert-rules-configuration
          mountPath: "/alert-rules"
          readOnly: true
      volumes:
      - name: configuration
        configMap:
          name: prometheus-configmap
          items:
          - key: "prometheus.yml"
            path: "prometheus.yml"
      - name: alert-rules-configuration
        configMap:
          name: alert-rules-configmap
          items:
          - key: "alert-rules.yml"
            path: "alert-rules.yml"