apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: {{ .Values.prometheus.image }}:latest
        cmd: ["--config.file=/etc/prometheus/prometheus.yml"]
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: configuration
          mountPath: "/etc/prometheus"
          readOnly: true
      volumes:
      - name: configuration
        configMap:
          name: prometheus-config
          items:
          - key: "prometheus.yml"
            path: "prometheus.yml"