apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-thanos-store
spec:
  selector:
    app: thanos-store
  ports:
    - name: grpc
      protocol: TCP
      port: 20091
      targetPort: 20091
    - name: remote-http
      protocol: TCP
      port: 20902
      targetPort: 20902