apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier-deployment
  labels:
    app: thanos-querier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-querier
  template:
    metadata:
      labels:
        app: thanos-querier
    spec:
      containers:
      - name: thanos-querier
        image: {{ .Values.thanos.image }}
        ports:
        - containerPort: 10902
        command: ["thanos", "query"]
        args: 
          - "--store=thanos-receiver:10903"
      