name: CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install TFLint
        uses: lablabs/setup-tflint@v1.0.2
        with:
          tflint_version: latest
      - name: Run linter
        run: |
          tflint
          tflint modules/blackbox_exporter
          tflint modules/corsham_bastion
          tflint modules/grafana
          tflint modules/monitoring_platform
          tflint modules/prometheus
          tflint modules/snmp_exporter
      - name: Run formatter
        uses: ministryofjustice/github-actions/code-formatter@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
