name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.12.29
      - name: Install TFLint
        uses: lablabs/setup-tflint@v1.0.2
        with:
          tflint_version: latest
      - name: Run `terraform validate`
        run: |
          terraform init -backend=false
          terraform validate
      - name: Run linter
        run: |
          tflint
          tflint modules/blackbox_exporter
          tflint modules/corsham_bastion
          tflint modules/grafana
          tflint modules/monitoring_platform
          tflint modules/prometheus
          tflint modules/snmp_exporter
      - name: Run formatter
        uses: ministryofjustice/github-actions/code-formatter@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
